Mutation:
    type: object
    config:
        fields:
            syncUsers:
                type: "Boolean!"
                resolve: "@=service('App\\\\Infrastructure\\\\GraphQL\\\\Resolver\\\\UserResolver').syncUsers()"
