Query:
    type: object
    config:
        fields:
            me:
                type: "User"
                resolve: "@=service('App\\\\Infrastructure\\\\GraphQL\\\\Resolver\\\\UserResolver').me()"
            users:
                type: "[User!]!"
                resolve: "@=service('App\\\\Infrastructure\\\\GraphQL\\\\Resolver\\\\UserResolver').users()"
